sudo: false

branches:
  only:
    - master
    - 5.x
    - 6.x

language: java
before_install: JAVA_HOME=$(jdk_switcher home openjdk8) mvn --projects . gradle:invoke -Dtasks=:help
install: mvn install -DskipTests=true -P!standard-with-extra-repos
script: mvn verify
jdk:
  - openjdk7
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
